server:
    port: 8080
spring:
    jpa:
        showsql: true
        hibernate:
            ddl-auto: none
    datasource:
        name: test
        url: jdbc:mysql://127.0.0.1:3306/boot_activiti?useUnicode=true&characterEncoding=utf-8&useSSL=false
        username: root
        password: Admin123
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
